plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    maven { url = "https://cursemaven.com" }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    //NEXUSLIB
    modImplementation files("nexuslib-fabric-1.21.1-1.1.5.jar")

    //APPLESKIN
    modCompileOnly ("curse.maven:appleskin-248787:5864741")

    //JEI
    modCompileOnlyApi ("curse.maven:jei-238222:6075246")

    //EMI
    modCompileOnlyApi ("curse.maven:emi-580555:8081407")

    modApi "me.shedaniel.cloth:cloth-config-fabric:15.0.140"
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName = "bountifulfares.refmap.json"
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            inherit client
            name "Data Generation"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../common/src/main/generated/")}"
            vmArg "-Dfabric-api.datagen.modid=bountifulfares"

            runDir "build/datagen"
        }
    }
}

sourceSets.main.resources { srcDir project(":common").file('src/main/generated/').getAbsolutePath() }

remapJar {
    destinationDirectory = rootProject.project(':common').layout.buildDirectory.dir('libs').get().asFile
}