# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.0.2
group=net.hecco.bountifulfares
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Bountiful Fares
mod_author=Hecco
mod_id=bountifulfares
license=All Rights Reserved (Modified)
credits=
description=Adds new content to the food and farming side of Minecraft!
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_loader_version=0.16.14
fabric_version=0.116.4+1.21.1

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.206
neoforge_loader_version_range=[4,)

# NexusLib
fabric_nexuslib=6669658
neoforge_nexuslib=6669659
nexuslib_version_range=[1.1.2-BETA2,)
nexuslib_version=1.1.2

# Appleskin
fabric_appleskin_version=3.0.6

modmenu_version=11.0.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
