package net.hecco.bountifulfares.registry.misc;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.hecco.bountifulfares.BountifulFares;
import net.hecco.bountifulfares.compat.appledog.AppledogBlocks;
import net.hecco.bountifulfares.compat.arts_and_crafts.ArtsAndCraftsBlocks;
import net.hecco.bountifulfares.compat.dye_depot.DyeDepotBlocks;
import net.hecco.bountifulfares.compat.excessive_building.ExcessiveBuildingBlocks;
import net.hecco.bountifulfares.compat.farmersdelight.FarmersDelightItemGroups;
import net.hecco.bountifulfares.compat.mint.MintBlocks;
import net.hecco.bountifulfares.compat.natures_spirit.NaturesSpiritBlocks;
import net.hecco.bountifulfares.compat.spawn.SpawnBlocks;
import net.hecco.bountifulfares.compat.twigs.TwigsBlocks;
import net.hecco.bountifulfares.registry.content.BFBlocks;
import net.hecco.bountifulfares.registry.content.BFItems;
import net.hecco.bountifulfares.registry.content.BFPotions;
import net.hecco.bountifulfares.registry.tags.BFBlockTags;
import net.hecco.bountifulfares.trellis.TrellisUtil;
import net.hecco.bountifulfares.trellis.trellis_parts.TrellisVariant;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.Registry;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.NbtOps;
import net.minecraft.nbt.Tag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.RegistryOps;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.decoration.Painting;
import net.minecraft.world.entity.decoration.PaintingVariant;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.component.CustomData;

import java.util.Comparator;
import java.util.Objects;
import java.util.function.Predicate;

public class BFItemGroups {

    private static final Comparator<Holder<PaintingVariant>> PAINTING_VARIANT_COMPARATOR = Comparator.comparing(Holder::value, Comparator.comparingInt((paintingVariant) -> 16 * 16));

    public static CreativeModeTab BOUNTIFUL_FARES = Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB, ResourceLocation.fromNamespaceAndPath(BountifulFares.MOD_ID, "bountiful_fares"),
            FabricItemGroup.builder().title(Component.translatable("itemgroup.bountiful_fares"))
                    .icon(() -> new ItemStack(BFItems.PASSION_FRUIT)).displayItems((displayContext, entries) -> {
                        entries.accept(BFBlocks.APPLE_LOG);
                        entries.accept(BFBlocks.APPLE_WOOD);
                        entries.accept(BFBlocks.STRIPPED_APPLE_LOG);
                        entries.accept(BFBlocks.STRIPPED_APPLE_WOOD);
                        entries.accept(BFBlocks.APPLE_LEAVES);
                        entries.accept(BFBlocks.FLOWERING_APPLE_LEAVES);
                        entries.accept(Items.APPLE);
                        entries.accept(BFBlocks.APPLE_BLOCK);
                        entries.accept(BFBlocks.APPLE_SAPLING);
                        entries.accept(BFBlocks.ORANGE_LOG);
                        entries.accept(BFBlocks.ORANGE_WOOD);
                        entries.accept(BFBlocks.STRIPPED_ORANGE_LOG);
                        entries.accept(BFBlocks.STRIPPED_ORANGE_WOOD);
                        entries.accept(BFBlocks.ORANGE_LEAVES);
                        entries.accept(BFBlocks.FLOWERING_ORANGE_LEAVES);
                        entries.accept(BFItems.ORANGE);
                        entries.accept(BFBlocks.ORANGE_BLOCK);
                        entries.accept(BFBlocks.ORANGE_SAPLING);
                        entries.accept(BFBlocks.LEMON_LOG);
                        entries.accept(BFBlocks.LEMON_WOOD);
                        entries.accept(BFBlocks.STRIPPED_LEMON_LOG);
                        entries.accept(BFBlocks.STRIPPED_LEMON_WOOD);
                        entries.accept(BFBlocks.LEMON_LEAVES);
                        entries.accept(BFBlocks.FLOWERING_LEMON_LEAVES);
                        entries.accept(BFItems.LEMON);
                        entries.accept(BFBlocks.LEMON_BLOCK);
                        entries.accept(BFBlocks.LEMON_SAPLING);
                        entries.accept(BFBlocks.PLUM_LOG);
                        entries.accept(BFBlocks.PLUM_WOOD);
                        entries.accept(BFBlocks.STRIPPED_PLUM_LOG);
                        entries.accept(BFBlocks.STRIPPED_PLUM_WOOD);
                        entries.accept(BFBlocks.PLUM_LEAVES);
                        entries.accept(BFBlocks.FLOWERING_PLUM_LEAVES);
                        entries.accept(BFItems.PLUM);
                        entries.accept(BFBlocks.PLUM_BLOCK);
                        entries.accept(BFBlocks.PLUM_SAPLING);
                        entries.accept(BFBlocks.GOLDEN_APPLE_LOG);
                        entries.accept(BFBlocks.GOLDEN_APPLE_WOOD);
                        entries.accept(BFBlocks.GOLDEN_APPLE_LEAVES);
                        entries.accept(BFBlocks.FLOWERING_GOLDEN_APPLE_LEAVES);
                        entries.accept(Items.GOLDEN_APPLE);
                        entries.accept(BFBlocks.GOLDEN_APPLE_BLOCK);
                        entries.accept(BFBlocks.GOLDEN_APPLE_SAPLING);
                        entries.accept(BFBlocks.HOARY_LOG);
                        entries.accept(BFBlocks.HOARY_WOOD);
                        entries.accept(BFBlocks.STRIPPED_HOARY_LOG);
                        entries.accept(BFBlocks.STRIPPED_HOARY_WOOD);
                        entries.accept(BFBlocks.HOARY_PLANKS);
                        entries.accept(BFBlocks.HOARY_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.HOARY_VERTICAL_STAIRS);
                        entries.accept(BFBlocks.HOARY_SLAB);
                        entries.accept(TwigsBlocks.HOARY_TABLE);
                        entries.accept(BFBlocks.HOARY_FENCE);
                        entries.accept(BFBlocks.HOARY_FENCE_GATE);
                        entries.accept(BFBlocks.HOARY_DOOR);
                        entries.accept(BFBlocks.HOARY_TRAPDOOR);
                        entries.accept(BFBlocks.HOARY_PRESSURE_PLATE);
                        entries.accept(BFBlocks.HOARY_BUTTON);
                        entries.accept(BFItems.HOARY_SIGN);
                        entries.accept(BFItems.HOARY_HANGING_SIGN);
                        entries.accept(BFItems.HOARY_BOAT);
                        entries.accept(BFItems.HOARY_CHEST_BOAT);
                        entries.accept(ExcessiveBuildingBlocks.CHISELED_HOARY_PLANKS);
                        entries.accept(ExcessiveBuildingBlocks.HOARY_MOSAIC);
                        entries.accept(ExcessiveBuildingBlocks.HOARY_MOSAIC_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.HOARY_MOSAIC_VERTICAL_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.HOARY_MOSAIC_SLAB);
                        entries.accept(ExcessiveBuildingBlocks.HOARY_LADDER);
                        entries.accept(BFBlocks.HOARY_LEAVES);
                        entries.accept(BFItems.HOARY_APPLE);
                        entries.accept(BFBlocks.HOARY_APPLE_BLOCK);
                        entries.accept(BFBlocks.HOARY_APPLE_SAPLING);
                        entries.accept(BFBlocks.WALNUT_LOG);
                        entries.accept(BFBlocks.WALNUT_WOOD);
                        entries.accept(BFBlocks.STRIPPED_WALNUT_LOG);
                        entries.accept(BFBlocks.STRIPPED_WALNUT_WOOD);
                        entries.accept(BFBlocks.WALNUT_PLANKS);
                        entries.accept(BFBlocks.WALNUT_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_VERTICAL_STAIRS);
                        entries.accept(BFBlocks.WALNUT_SLAB);
                        entries.accept(TwigsBlocks.WALNUT_TABLE);
                        entries.accept(BFBlocks.WALNUT_FENCE);
                        entries.accept(BFBlocks.WALNUT_FENCE_GATE);
                        entries.accept(BFBlocks.WALNUT_DOOR);
                        entries.accept(BFBlocks.WALNUT_TRAPDOOR);
                        entries.accept(BFBlocks.WALNUT_PRESSURE_PLATE);
                        entries.accept(BFBlocks.WALNUT_BUTTON);
                        entries.accept(BFItems.WALNUT_SIGN);
                        entries.accept(BFItems.WALNUT_HANGING_SIGN);
                        entries.accept(BFItems.WALNUT_BOAT);
                        entries.accept(BFItems.WALNUT_CHEST_BOAT);
                        entries.accept(ExcessiveBuildingBlocks.CHISELED_WALNUT_PLANKS);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MOSAIC);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MOSAIC_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MOSAIC_VERTICAL_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MOSAIC_SLAB);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_LADDER);
                        entries.accept(BFBlocks.WALNUT_LEAVES);
                        entries.accept(BFBlocks.WALNUT_SAPLING);
                        entries.accept(BFItems.WALNUT);
                        entries.accept(BFBlocks.WALNUT_MULCH);
                        entries.accept(BFBlocks.WALNUT_MULCH_BLOCK);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MULCH_BRICKS);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MULCH_BRICK_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MULCH_BRICK_SLAB);
                        entries.accept(ExcessiveBuildingBlocks.WALNUT_MULCH_BRICK_WALL);
                        entries.accept(BFBlocks.PALM_LOG);
                        entries.accept(BFBlocks.PALM_WOOD);
                        entries.accept(BFBlocks.STRIPPED_PALM_LOG);
                        entries.accept(BFBlocks.STRIPPED_PALM_WOOD);
                        entries.accept(BFBlocks.PALM_CROWN);
                        entries.accept(BFItems.PALM_FROND);
                        entries.accept(BFItems.COCONUT);
                        entries.accept(BFItems.COCONUT_HALF);
                        entries.accept(BFBlocks.COCONUT_CANDLE);
                        entries.accept(BFItems.COCONUT_COIR);
                        entries.accept(BFBlocks.PACKED_COCONUT_COIR);
                        entries.accept(BFBlocks.COIR_CARPET);
                        entries.accept(BFBlocks.COIR_BRICKS);
                        entries.accept(BFBlocks.COIR_BRICK_STAIRS);
                        entries.accept(BFBlocks.COIR_BRICK_SLAB);
                        entries.accept(BFBlocks.COIR_BRICK_WALL);
                        entries.accept(BFBlocks.PALM_MULCH);
                        entries.accept(BFBlocks.PALM_MULCH_BLOCK);
                        entries.accept(ExcessiveBuildingBlocks.PALM_MULCH_BRICKS);
                        entries.accept(ExcessiveBuildingBlocks.PALM_MULCH_BRICK_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.PALM_MULCH_BRICK_SLAB);
                        entries.accept(ExcessiveBuildingBlocks.PALM_MULCH_BRICK_WALL);
                        entries.accept(BFBlocks.OAK_PICKETS);
                        entries.accept(BFBlocks.SPRUCE_PICKETS);
                        entries.accept(BFBlocks.BIRCH_PICKETS);
                        entries.accept(BFBlocks.JUNGLE_PICKETS);
                        entries.accept(BFBlocks.ACACIA_PICKETS);
                        entries.accept(BFBlocks.DARK_OAK_PICKETS);
                        entries.accept(BFBlocks.MANGROVE_PICKETS);
                        entries.accept(BFBlocks.CHERRY_PICKETS);
                        entries.accept(BFBlocks.BAMBOO_PICKETS);
                        entries.accept(BFBlocks.WALNUT_PICKETS);

                        entries.accept(MintBlocks.WINTERGREEN_PICKETS);

                        entries.accept(NaturesSpiritBlocks.REDWOOD_PICKETS);
                        entries.accept(NaturesSpiritBlocks.SUGI_PICKETS);
                        entries.accept(NaturesSpiritBlocks.WISTERIA_PICKETS);
                        entries.accept(NaturesSpiritBlocks.FIR_PICKETS);
                        entries.accept(NaturesSpiritBlocks.WILLOW_PICKETS);
                        entries.accept(NaturesSpiritBlocks.ASPEN_PICKETS);
                        entries.accept(NaturesSpiritBlocks.MAPLE_PICKETS);
                        entries.accept(NaturesSpiritBlocks.CYPRESS_PICKETS);
                        entries.accept(NaturesSpiritBlocks.OLIVE_PICKETS);
                        entries.accept(NaturesSpiritBlocks.JOSHUA_PICKETS);
                        entries.accept(NaturesSpiritBlocks.GHAF_PICKETS);
                        entries.accept(NaturesSpiritBlocks.PALO_VERDE_PICKETS);
                        entries.accept(NaturesSpiritBlocks.COCONUT_PICKETS);
                        entries.accept(NaturesSpiritBlocks.CEDAR_PICKETS);
                        entries.accept(NaturesSpiritBlocks.LARCH_PICKETS);
                        entries.accept(NaturesSpiritBlocks.MAHOGANY_PICKETS);
                        entries.accept(NaturesSpiritBlocks.SAXAUL_PICKETS);

                        entries.accept(ExcessiveBuildingBlocks.ANCIENT_PICKETS);

                        entries.accept(SpawnBlocks.ROTTEN_PICKETS);

                        entries.accept(ArtsAndCraftsBlocks.CORK_PICKETS);

                        entries.accept(BFBlocks.HOARY_PICKETS);
                        entries.accept(BFBlocks.CRIMSON_PICKETS);
                        entries.accept(BFBlocks.WARPED_PICKETS);
                        entries.accept(BFBlocks.IRON_RAILING);
                        entries.accept(BFItems.FELDSPAR);
                        entries.accept(BFBlocks.FELDSPAR_BLOCK);
                        entries.accept(BFBlocks.CUT_FELDSPAR_BLOCK);
                        entries.accept(BFBlocks.FELDSPAR_BRICKS);
                        entries.accept(BFBlocks.FELDSPAR_BRICK_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.FELDSPAR_BRICK_VERTICAL_STAIRS);
                        entries.accept(BFBlocks.FELDSPAR_BRICK_SLAB);
                        entries.accept(BFBlocks.FELDSPAR_BRICK_WALL);
                        entries.accept(BFBlocks.FELDSPAR_LANTERN);
                        entries.accept(TwigsBlocks.FELDSPAR_LAMP);
                        entries.accept(BFBlocks.TINGED_GLASS);
                        entries.accept(BFItems.CERAMIC_CLAY);
                        entries.accept(BFBlocks.CERAMIC_CLAY_BLOCK);
                        entries.accept(BFItems.CERAMIC_TILE);
                        entries.accept(BFBlocks.CERAMIC_TILES);
                        entries.accept(BFBlocks.CERAMIC_TILE_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.CERAMIC_TILE_VERTICAL_STAIRS);
                        entries.accept(BFBlocks.CERAMIC_TILE_SLAB);
                        //entries.add(BFBlocks.CERAMIC_TILE_WALL);
                        entries.accept(BFBlocks.CRACKED_CERAMIC_TILES);
                        entries.accept(BFBlocks.CERAMIC_TILE_PILLAR);
                        entries.accept(BFBlocks.CERAMIC_MOSAIC);
                        entries.accept(BFBlocks.CERAMIC_MOSAIC_STAIRS);
                        entries.accept(ExcessiveBuildingBlocks.CERAMIC_MOSAIC_VERTICAL_STAIRS);
                        entries.accept(BFBlocks.CERAMIC_MOSAIC_SLAB);
                        //entries.add(BFBlocks.CERAMIC_MOSAIC_WALL);
                        entries.accept(BFBlocks.CERAMIC_DOOR);
                        entries.accept(BFBlocks.CERAMIC_TRAPDOOR);
                        entries.accept(BFBlocks.CERAMIC_PRESSURE_PLATE);
                        entries.accept(BFBlocks.CERAMIC_BUTTON);
                        entries.accept(BFBlocks.CERAMIC_LEVER);
                        entries.accept(BFBlocks.CERAMIC_DISH);
                        entries.accept(BFBlocks.SOLID_CERAMIC);
                        entries.accept(BFItems.ARTISAN_BRUSH);
                        entries.accept(BFItems.SUN_HAT);

                        entries.accept(BFBlocks.WHITE_JACK_O_STRAW);
                        entries.accept(BFBlocks.LIGHT_GRAY_JACK_O_STRAW);
                        entries.accept(BFBlocks.GRAY_JACK_O_STRAW);
                        entries.accept(BFBlocks.BLACK_JACK_O_STRAW);
                        entries.accept(MintBlocks.ACORN_JACK_O_STRAW);
                        entries.accept(BFBlocks.BROWN_JACK_O_STRAW);
                        entries.accept(MintBlocks.MAROON_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.MAROON_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.ROSE_JACK_O_STRAW);
                        entries.accept(BFBlocks.RED_JACK_O_STRAW);
                        entries.accept(MintBlocks.PEACH_JACK_O_STRAW);
                        entries.accept(MintBlocks.VERMILION_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.CORAL_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.GINGER_JACK_O_STRAW);
                        entries.accept(BFBlocks.ORANGE_JACK_O_STRAW);
                        entries.accept(MintBlocks.AMBER_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.TAN_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.BEIGE_JACK_O_STRAW);
                        entries.accept(BFBlocks.YELLOW_JACK_O_STRAW);
                        entries.accept(MintBlocks.BANANA_JACK_O_STRAW);
                        entries.accept(MintBlocks.ARTICHOKE_JACK_O_STRAW);
                        entries.accept(MintBlocks.MOLD_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.AMBER_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.OLIVE_JACK_O_STRAW);
                        entries.accept(BFBlocks.LIME_JACK_O_STRAW);
                        entries.accept(MintBlocks.SAGE_JACK_O_STRAW);
                        entries.accept(MintBlocks.SAP_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.FOREST_JACK_O_STRAW);
                        entries.accept(BFBlocks.GREEN_JACK_O_STRAW);
                        entries.accept(MintBlocks.SHAMROCK_JACK_O_STRAW);
                        entries.accept(MintBlocks.MINT_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.VERDANT_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.TEAL_JACK_O_STRAW);
                        entries.accept(BFBlocks.CYAN_JACK_O_STRAW);
                        entries.accept(MintBlocks.CERULEAN_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.MINT_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.AQUA_JACK_O_STRAW);
                        entries.accept(BFBlocks.LIGHT_BLUE_JACK_O_STRAW);
                        entries.accept(MintBlocks.NAVY_JACK_O_STRAW);
                        entries.accept(BFBlocks.BLUE_JACK_O_STRAW);
                        entries.accept(MintBlocks.PERIWINKLE_JACK_O_STRAW);
                        entries.accept(MintBlocks.GRAPE_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.SLATE_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.NAVY_JACK_O_STRAW);
                        entries.accept(DyeDepotBlocks.INDIGO_JACK_O_STRAW);
                        entries.accept(BFBlocks.PURPLE_JACK_O_STRAW);
                        entries.accept(MintBlocks.INDIGO_JACK_O_STRAW);
                        entries.accept(BFBlocks.MAGENTA_JACK_O_STRAW);
                        entries.accept(MintBlocks.MAUVE_JACK_O_STRAW);
                        entries.accept(MintBlocks.VELVET_JACK_O_STRAW);
                        entries.accept(MintBlocks.FUCHSIA_JACK_O_STRAW);
                        entries.accept(BFBlocks.PINK_JACK_O_STRAW);
                        entries.accept(BFBlocks.GRASSY_DIRT);
                        entries.accept(BFBlocks.WILD_WHEAT);
                        entries.accept(BFBlocks.WILD_CARROTS);
                        entries.accept(BFBlocks.WILD_POTATOES);
                        entries.accept(BFBlocks.WILD_BEETROOTS);
                        entries.accept(BFBlocks.WILD_MAIZE);
                        entries.accept(BFBlocks.WILD_LEEKS);
                        entries.accept(BFBlocks.WILD_PASSION_FRUIT_VINE);
                        entries.accept(BFBlocks.WILD_ELDERBERRY_VINE);
                        entries.accept(BFItems.GRASS_SEEDS);
                        entries.accept(BFItems.SWEET_BERRY_PIPS);
                        entries.accept(BFItems.MAIZE_SEEDS);
                        entries.accept(BFItems.LEEK_SEEDS);
                        entries.accept(BFItems.SPONGEKIN_SEEDS);
                        entries.accept(BFItems.LAPISBERRY_SEEDS);
                        entries.accept(BFItems.HOARY_SEEDS);
                        entries.accept(BFItems.MAIZE);
                        entries.accept(BFItems.LEEK);
                        for (TrellisVariant trellis : TrellisUtil.TrellisVariants) {
                            if (Objects.equals(trellis.getModId(), BountifulFares.MOD_ID)) {
                                if (TrellisUtil.getTrellisFromVariant(trellis) != null) {
                                    entries.accept(TrellisUtil.getTrellisFromVariant(trellis));
                                }
                            }
                        }
                        entries.accept(TrellisUtil.getTrellisFromVariant(MintBlocks.WINTERGREEN));
                        if (BountifulFares.isModLoaded(BountifulFares.NATURES_SPIRIT_MOD_ID)) {
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.REDWOOD));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.SUGI));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.WISTERIA));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.FIR));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.WILLOW));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.ASPEN));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.MAPLE));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.CYPRESS));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.OLIVE));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.JOSHUA));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.GHAF));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.PALO_VERDE));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.COCONUT));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.CEDAR));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.LARCH));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.MAHOGANY));
                            entries.accept(TrellisUtil.getTrellisFromVariant(NaturesSpiritBlocks.SAXAUL));
                        }
                        entries.accept(TrellisUtil.getTrellisFromVariant(ExcessiveBuildingBlocks.ANCIENT));
                        entries.accept(TrellisUtil.getTrellisFromVariant(SpawnBlocks.ROTTEN));
                        entries.accept(TrellisUtil.getTrellisFromVariant(ArtsAndCraftsBlocks.CORK));
//                        if (BountifulFares.isModLoaded(BountifulFares.WILDER_WILD_MOD_ID)) {
//                            entries.add(TrellisUtil.getTrellisFromVariant(BFTrellises.BAOBAB));
//                            entries.add(TrellisUtil.getTrellisFromVariant(BFTrellises.WW_CYPRESS));
//                            entries.add(TrellisUtil.getTrellisFromVariant(BFTrellises.PALM));
//                        }
                        entries.accept(BFItems.PASSION_FRUIT);
                        entries.accept(BFItems.ELDERBERRIES);
                        entries.accept(BFItems.LAPISBERRIES);
                        entries.accept(BFItems.TEA_BERRIES);
                        entries.accept(BFItems.TEA_LEAVES);
                        entries.accept(BFItems.DRIED_TEA_LEAVES);
                        entries.accept(BFBlocks.CHAMOMILE_FLOWERS);
                        entries.accept(BFBlocks.HONEYSUCKLE);
                        entries.accept(BFBlocks.VIOLET_BELLFLOWER);
                        entries.accept(BFBlocks.SPONGEKIN);
                        entries.accept(BFItems.SPONGEKIN_SLICE);
                        entries.accept(BFBlocks.PRISMARINE_BLOSSOM);
                        entries.accept(BFBlocks.GRISTMILL);
                        entries.accept(BFItems.FLOUR);
                        entries.accept(BFItems.GREEN_TEA_BLEND);
                        entries.accept(BFItems.BLACK_TEA_BLEND);
                        entries.accept(BFItems.CHAMOMILE_TEA_BLEND);
                        entries.accept(BFItems.HONEYSUCKLE_TEA_BLEND);
                        entries.accept(BFItems.BELLFLOWER_TEA_BLEND);
                        entries.accept(BFItems.TORCHFLOWER_TEA_BLEND);
                        entries.accept(BFItems.GREEN_TEA_BOTTLE);
                        entries.accept(BFItems.BLACK_TEA_BOTTLE);
                        entries.accept(BFItems.CHAMOMILE_TEA_BOTTLE);
                        entries.accept(BFItems.HONEYSUCKLE_TEA_BOTTLE);
                        entries.accept(BFItems.BELLFLOWER_TEA_BOTTLE);
                        entries.accept(BFItems.TORCHFLOWER_TEA_BOTTLE);
                        entries.accept(BFBlocks.GREEN_TEA_CANDLE);
                        entries.accept(BFBlocks.BLACK_TEA_CANDLE);
                        entries.accept(BFBlocks.CHAMOMILE_CANDLE);
                        entries.accept(BFBlocks.HONEYSUCKLE_CANDLE);
                        entries.accept(BFBlocks.BELLFLOWER_CANDLE);
                        entries.accept(BFBlocks.TORCHFLOWER_CANDLE);
                        entries.accept(BFBlocks.WALNUT_CANDLE);
                        entries.accept(BFBlocks.FERMENTATION_VESSEL);
                        entries.accept(BFItems.ELDERBERRY_WINE_BOTTLE);
                        entries.accept(BFItems.LAPISBERRY_WINE_BOTTLE);
                        entries.accept(BFItems.MEAD_BOTTLE);
                        entries.accept(BFItems.COCONUT_MILK_BOTTLE);
                        entries.accept(BFItems.JAR);
                        entries.accept(BFItems.APPLE_CIDER_JAR);
                        entries.accept(BFItems.PLUM_CIDER_JAR);
                        entries.accept(BFItems.HOARY_CIDER_JAR);
                        entries.accept(BFItems.APPLE_COMPOTE_JAR);
                        entries.accept(BFItems.ORANGE_COMPOTE_JAR);
                        entries.accept(BFItems.LEMON_COMPOTE_JAR);
                        entries.accept(BFItems.PLUM_COMPOTE_JAR);
                        entries.accept(BFItems.HOARY_COMPOTE_JAR);
                        entries.accept(BFItems.CITRUS_ESSENCE);
                        entries.accept(BFItems.PICKLED_SPONGEKIN);
                        entries.accept(PotionContents.createItemStack(Items.POTION, BFPotions.ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.POTION, BFPotions.LONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.POTION, BFPotions.STRONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.SPLASH_POTION, BFPotions.ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.SPLASH_POTION, BFPotions.LONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.SPLASH_POTION, BFPotions.STRONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.LINGERING_POTION, BFPotions.ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.LINGERING_POTION, BFPotions.LONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.LINGERING_POTION, BFPotions.STRONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.TIPPED_ARROW, BFPotions.ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.TIPPED_ARROW, BFPotions.LONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.TIPPED_ARROW, BFPotions.STRONG_ACIDIC));
                        entries.accept(PotionContents.createItemStack(Items.POTION, BFPotions.STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.POTION, BFPotions.LONG_STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.SPLASH_POTION, BFPotions.STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.SPLASH_POTION, BFPotions.LONG_STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.LINGERING_POTION, BFPotions.STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.LINGERING_POTION, BFPotions.LONG_STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.TIPPED_ARROW, BFPotions.STUPOR));
                        entries.accept(PotionContents.createItemStack(Items.TIPPED_ARROW, BFPotions.LONG_STUPOR));
                        entries.accept(BFBlocks.ARTISAN_BREAD);
                        entries.accept(BFItems.ARTISAN_COOKIE);
                        entries.accept(BFBlocks.APPLE_PIE);
                        entries.accept(BFBlocks.ORANGE_PIE);
                        entries.accept(BFBlocks.LEMON_PIE);
                        entries.accept(BFBlocks.PLUM_PIE);
                        entries.accept(BFBlocks.HOARY_PIE);
                        entries.accept(Items.PUMPKIN_PIE);
                        entries.accept(BFBlocks.MELON_PIE);
                        entries.accept(BFBlocks.PASSION_FRUIT_TART);
                        entries.accept(BFBlocks.ELDERBERRY_TART);
                        entries.accept(BFBlocks.GLOW_BERRY_TART);
                        entries.accept(BFBlocks.SWEET_BERRY_TART);
                        entries.accept(BFBlocks.LAPISBERRY_TART);
                        entries.accept(BFBlocks.COCOA_CAKE);
                        entries.accept(BFBlocks.COCONUT_CAKE);
                        entries.accept(BFBlocks.SPONGE_CAKE);
                        entries.accept(BFItems.WALNUT_COOKIE);
                        entries.accept(BFItems.MAIZE_BREAD);
                        entries.accept(BFItems.POPPED_MAIZE);
                        entries.accept(BFItems.COOKED_EGG);
                        entries.accept(BFItems.FOREST_MEDLEY);
                        entries.accept(BFItems.ARID_MEDLEY);
                        entries.accept(BFItems.MEADOW_MEDLEY);
                        entries.accept(BFItems.MIRE_MEDLEY);
                        entries.accept(BFItems.COASTAL_MEDLEY);
                        entries.accept(BFItems.TROPICAL_MEDLEY);
                        entries.accept(BFItems.MUSHROOM_STUFFED_POTATO);
                        entries.accept(BFItems.BERRY_STUFFED_POTATO);
                        entries.accept(BFItems.MAIZE_STUFFED_POTATO);
                        entries.accept(BFItems.STUFFED_HOARY_APPLE);
                        entries.accept(BFItems.LEEK_STEW);
                        entries.accept(BFItems.FISH_STEW);
                        entries.accept(BFItems.APPLE_STEW);
                        entries.accept(BFItems.COCONUT_STEW);
                        entries.accept(BFItems.STONE_STEW);
                        entries.accept(BFItems.BOUNTIFUL_STEW);
                        entries.accept(BFItems.SEA_SALAD);
                        entries.accept(BFItems.PASSION_GLAZED_SALMON);
                        entries.accept(BFItems.COCONUT_CRUSTED_COD);
                        entries.accept(BFItems.CRUSTED_BEEF);
                        entries.accept(BFItems.CRIMSON_CHOW);
                        entries.accept(BFItems.WARPED_CHOW);
                        entries.accept(BFItems.CUSTARD);
                        entries.accept(BFItems.PIQUANT_CUSTARD);
                        entries.accept(BFItems.PASSION_CUSTARD);
                        entries.accept(BFItems.COCOA_CUSTARD);
                        entries.accept(BFItems.ANCIENT_CUSTARD);
                        entries.accept(BFItems.CANDY);
                        entries.accept(BFItems.PIQUANT_CANDY);
                        entries.accept(BFItems.SOUR_CANDY);
                        entries.accept(BFItems.BITTER_CANDY);
                        entries.accept(BFItems.STRANGE_CANDY);
                        entries.accept(BFItems.CANDIED_APPLE);
                        entries.accept(BFItems.CANDIED_PLUM);
                        entries.accept(BFItems.CANDIED_ORANGE);
                        entries.accept(BFItems.CANDIED_LEMON);
//                        displayContext.lookup().getOptionalWrapper(RegistryKeys.PAINTING_VARIANT).ifPresent((wrapper) -> {
//                            addPaintings(entries, wrapper, (registryEntry) -> registryEntry.isIn(BFBlockTags.PAINTINGS), ItemGroup.StackVisibility.PARENT_AND_SEARCH_TABS);
//                        });
                        displayContext.holders().lookup(Registries.PAINTING_VARIANT).ifPresent((registryWrapper) -> {
                            addPaintings(entries, displayContext.holders(), registryWrapper, (registryEntry) -> registryEntry.is(BFBlockTags.PAINTINGS), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
                        });
                        entries.accept(AppledogBlocks.APPLEDOG_BLOCK);

                    }).build());

    private static void addPaintings(CreativeModeTab.Output entries, HolderLookup.Provider registryLookup, HolderLookup.RegistryLookup<PaintingVariant> registryWrapper, Predicate<Holder<PaintingVariant>> filter, CreativeModeTab.TabVisibility stackVisibility) {
        RegistryOps<Tag> registryOps = registryLookup.createSerializationContext(NbtOps.INSTANCE);
        registryWrapper.listElements().filter(filter).sorted(PAINTING_VARIANT_COMPARATOR).forEach((paintingVariantEntry) -> {
            CustomData nbtComponent = CustomData.EMPTY.update(registryOps, Painting.VARIANT_MAP_CODEC, paintingVariantEntry).getOrThrow().update((nbt) -> {
                nbt.putString("id", "minecraft:painting");
            });
            ItemStack itemStack = new ItemStack(Items.PAINTING);
            itemStack.set(DataComponents.ENTITY_DATA, nbtComponent);
            entries.accept(itemStack, stackVisibility);
        });
    }
    public static void registerItemGroups()
    {
        // Can be used to register item mod tabs if the mod is loaded
        if (BountifulFares.isModLoaded(BountifulFares.FARMERS_DELIGHT_MOD_ID)) FarmersDelightItemGroups.registerModItemTabs();

        // Oh my god kaupenjoe reference        - Artyrian
        //        BountifulFares.LOGGER.info("Registering Item Group Entries for " + BountifulFares.MOD_ID);
    }
}
