plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

repositories {
    maven { url = "https://cursemaven.com" }
    maven { url "https://maven.shedaniel.me/" }
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    //NEXUSLIB
//    implementation "curse.maven:heccolib-1279113:${neoforge_heccolib}"
    implementation files("nexuslib-neoforge-1.21.1-1.1.4.jar")
//    api "me.shedaniel.cloth:cloth-config-neoforge:15.0.140"

    //EVERY COMPAT
    compileOnlyApi "curse.maven:every-compat-628539:7010172"
    compileOnlyApi "curse.maven:selene-499980:7017282"

    //JEI
    compileOnlyApi ("curse.maven:jei-238222:6829086")

    //EMI
    compileOnlyApi ("curse.maven:emi-580555:8081408")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

