plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    maven { url = "https://cursemaven.com" }
    maven { url "https://maven.shedaniel.me/" }
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    //NEXUSLIB
    implementation files("nexuslib-neoforge-1.21.1-1.1.2.jar")

    //APPLESKIN
    compileOnly files("appleskin-neoforge-mc1.21-3.0.7.jar")

    //JEI
    compileOnlyApi ("curse.maven:jei-238222:6829086")

    //EMI
    compileOnlyApi ("curse.maven:emi-580555:6420931")
}

sourceSets.main.resources { srcDir project(":common").file('src/main/generated/').getAbsolutePath() }